spring:
  application:
    name: basket
  profiles:
    active: common
server:
  port: 8082
microService:
  quarryService: http://localhost:8081
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus