name: 'Backend: Build & Push Images to GHCR'

on:
  workflow_run:
    workflows: ['Backend: Tests']
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  backend-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - obelix-webshop
          - obelix-quarry-impl
          - obelix-basket-impl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image names
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Build & Push
      - name: Build & Push Backend Service
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.service }}:${{ github.sha }}