name: Build & Push Images to GHCR

on:
  workflow_run:
    workflows: ['Backend Tests']
    types: [completed]
    branches:
      - 'main'



jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker tags
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV


      # Docker metadata
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.OWNER_LC }}/backend
            ghcr.io/${{ env.OWNER_LC }}/frontend
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      # Backend build
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/backend:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      # Frontend build
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: menhir-webshop
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/menhir-webshop:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}